# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - storming0x/yearn-vaults@0.4.3-sol8
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.0
  - connext/nxtp@0.2.0-beta.10

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.11
    remappings:
      - "@yearnvaults=storming0x/yearn-vaults@0.4.3-sol8"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
      - "@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.0/contracts"
      - "@connext=connext/nxtp@0.2.0-beta.10/packages/deployments/contracts/contracts/core/connext/"

reports:
  exclude_contracts:
    - SafeMath
